version: '3.1'
services:
    web:
        build: .
        ports:
            - "8080:5000"
        volumes:
            - .:/code
    nginx:
        image: nginx:1.16.1  
        ports:
            - 80:80

